---
- stat:
    path: "{{ swap_location }}"
  register: swap_file

- debug:
    msg: "swap_file.stat exists"
    var: swap_file.stat.exists

- debug:
    msg: "swap_file.stat is a regular file"
    var: swap_file.stat.isreg

- debug:
    msg: "Swap_file size does not equal swap_size_mb * 1024 * 1024"
    var: swap_file.stat.size is defined and swap_file.stat.size != (swap_size_mb * 1024 * 1024)

- include: remove_old_swap.yml
  when: swap_file.stat.exists and swap_file.stat.isreg and swap_file.stat.size != (swap_size_mb * 1024 * 1024)

- stat:
    path: "{{ swap_location }}"
  register: swap_file
  when: removed_swap.changed

- name: Swap | Write swap file
  sudo: yes
  command: |
    {% if swap_use_dd %}
    dd if=/dev/zero of={{ swap_location }} bs=1M count={{ swap_size_mb }}
    {% else %}
    fallocate -l {{ swap_size_mb }}MiB {{ swap_location }}
    {% endif %}
  args:
    creates: "{{ swap_location }}"
  when: not swap_file.stat.exists

- name: Swap | Change swap file permissions
  sudo: yes
  file:
    path: "{{ swap_location }}"
    owner: root
    group: root
    mode: 0600
    state: file

- name: Swap | Check swap file type
  command: "sudo file {{ swap_location }}"
  changed_when: false
  register: swapfile

- name: Swap | Make swap file
  command: "sudo mkswap {{ swap_location }}"
  when: swapfile.stdout.find('swap file') == -1

- name: Swap | Write swap entry in fstab
  sudo: yes
  mount:
    name: none
    src: "{{ swap_location }}"
    fstype: swap
    opts: sw
    passno: "0" # Quotes are needed *
    dump: "0"
    state: present

# * Quotes are needed becaue else it will be always marked as changed.
#   See this issue for more info: https://github.com/ansible/ansible-modules-core/issues/1868

- name: Swap | Mount swap
  command: "sudo swapon {{ swap_location }}"
  when: ansible_swaptotal_mb < 1 or (removed_swap is defined and removed_swap.changed)

- name: Swap | Configure the swappiness
  sudo: yes
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present
    reload: yes

- name: Swap | Configure the cache pressure
  sudo: yes
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swap_cache_pressure }}"
    state: present
    reload: yes
