---
- name: Unmount swap
  become: yes
  command: "swapoff {{ swap_location }}"

- name: Remove old swap
  become: yes
  file:
    path: "{{ swap_location }}"
    state: absent
  register: removed_swap
